<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="database-test suite" duration-ms="63" started-at="2019-03-01T06:47:54Z" finished-at="2019-03-01T06:47:54Z">
    <groups>
      <group name="planets">
        <method signature="TestDatabase.test1(java.lang.String)[pri:0, instance:com.abhay.practice.TestDatabase@7c16905e]" name="test1" class="com.abhay.practice.TestDatabase"/>
      </group> <!-- planets -->
      <group name="stars">
        <method signature="TestDatabase.test2()[pri:0, instance:com.abhay.practice.TestDatabase@7c16905e]" name="test2" class="com.abhay.practice.TestDatabase"/>
        <method signature="TestDatabase.test3()[pri:0, instance:com.abhay.practice.TestDatabase@7c16905e]" name="test3" class="com.abhay.practice.TestDatabase"/>
        <method signature="TestDatabase.test4()[pri:0, instance:com.abhay.practice.TestDatabase@7c16905e]" name="test4" class="com.abhay.practice.TestDatabase"/>
      </group> <!-- stars -->
    </groups>
    <test name="listener test" duration-ms="63" started-at="2019-03-01T06:47:54Z" finished-at="2019-03-01T06:47:54Z">
      <class name="com.abhay.practice.TestDatabase">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.abhay.practice.TestDatabase@7c16905e]" name="beforeSuite" is-config="true" duration-ms="41" started-at="2019-03-01T06:47:54Z" finished-at="2019-03-01T06:47:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.abhay.practice.TestDatabase@7c16905e]" name="setup" is-config="true" duration-ms="0" started-at="2019-03-01T06:47:54Z" finished-at="2019-03-01T06:47:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="test1(java.lang.String)[pri:0, instance:com.abhay.practice.TestDatabase@7c16905e]" name="test1" duration-ms="9" started-at="2019-03-01T06:47:54Z" finished-at="2019-03-01T06:47:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ abhay soni ]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="test2()[pri:0, instance:com.abhay.practice.TestDatabase@7c16905e]" name="test2" duration-ms="2" started-at="2019-03-01T06:47:54Z" finished-at="2019-03-01T06:47:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="FAIL" signature="test3()[pri:0, instance:com.abhay.practice.TestDatabase@7c16905e]" name="test3" duration-ms="5" started-at="2019-03-01T06:47:54Z" description="if this test fails test 4 will also not run" finished-at="2019-03-01T06:47:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.abhay.practice.TestDatabase.test3(TestDatabase.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="SKIP" signature="test4()[pri:0, instance:com.abhay.practice.TestDatabase@7c16905e]" name="test4" duration-ms="0" started-at="2019-03-01T06:47:54Z" description="This a dependent test depending on test3" depends-on-methods="com.abhay.practice.TestDatabase.test3" finished-at="2019-03-01T06:47:54Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestDatabase.test4()[pri:0, instance:com.abhay.practice.TestDatabase@7c16905e] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestDatabase.test4()[pri:0, instance:com.abhay.practice.TestDatabase@7c16905e] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
      </class> <!-- com.abhay.practice.TestDatabase -->
    </test> <!-- listener test -->
  </suite> <!-- database-test suite -->
</testng-results>
